global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: 
        - "worker:5001"
        - "api:80"
        - "localhost:9090"
